version: '3'

  services:
    nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
